# Funding options for GitHub Copilot Instructions

github: [vhcg77] # GitHub Sponsors
patreon: # Add your Patreon username if you have one
open_collective: # Add your Open Collective username if you have one
ko_fi: # Add your Ko-fi username if you have one
custom: ["https://github.com/vhcg77/github-copilot-instructions"] # Project repository
